import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import "./globals.css"
import LayoutProvider from "@/components/LayoutProvider"

const roboto = Roboto({ weight: ["100", "300", "400", "500", "700", "900"], subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function layout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <LayoutProvider>{children}</LayoutProvider>
            </body>
        </html>
    )
}
